import React, { useState } from 'react';
import { AlertTriangle, CheckCircle2, ClipboardList, Download, FileText, Plus, ShieldAlert, Wind, Zap } from 'lucide-react';
import { useDashboard } from '../DashboardContext';

const incidentHistory = [
  ['INC-001', 'Severe Blizzard', 'HIGH', 'Outdoor Operations', 'External work suspended during high wind', 'IN PROGRESS', '10:41 UTC'],
  ['INC-002', 'Equipment Failure', 'MEDIUM', 'Power', 'Generator inspection required', 'OPEN', '10:35 UTC'],
  ['INC-003', 'Medical Emergency', 'HIGH', 'Personnel', 'Medical response completed', 'RESOLVED', '09:20 UTC'],
  ['INC-004', 'Communication Loss', 'MEDIUM', 'Communication', 'Satellite link degraded', 'IN PROGRESS', '08:50 UTC'],
];

export default function RiskManagement() {
  const { data } = useDashboard();
  const [selected, setSelected] = useState(0);
  const [completed, setCompleted] = useState(() => (data?.emergencyChecklist || []).map((item) => item.checked));
  const weather = data?.currentWeather || {};
  const checklist = data?.emergencyChecklist || [
    { label: 'Verify personnel status' }, { label: 'Check power system' }, { label: 'Monitor heating demand' }, { label: 'Restrict external operations' }, { label: 'Record incident' },
  ];
  const reasons = data?.alertData?.reasons || [];
  const selectedIncident = incidentHistory[selected];
  const done = checklist.reduce((count, item, index) => count + (completed[index] || item.checked ? 1 : 0), 0);
  const risks = [
    ['High Weather Risk', data?.headerInfo?.time || '10:41 UTC', 'Wind increasing rapidly', 'Outdoor Operations', 'HIGH', Wind, 'text-rose-300'],
    ['Power System Watch', '10:35 UTC', 'High load detected', 'Power / Heating', 'WATCH', Zap, 'text-amber-300'],
    ['Communication Stable', '09:50 UTC', 'No action required', 'Communication', 'NORMAL', CheckCircle2, 'text-emerald-300'],
  ];
  return <div className="min-h-full overflow-x-hidden"><div className="mx-auto max-w-[1360px] px-4 pb-8 md:px-6"><header className="flex flex-wrap items-center justify-between gap-4 py-5"><div><h1 className="text-2xl font-bold text-white">Risk Management</h1><p className="text-xs text-slate-400">Active risks, emergency response, incidents and reports</p></div><button type="button" className="btn-gradient flex items-center gap-2 rounded-lg px-3 py-2 text-[10px] font-semibold"><Download size={13} />Export Report</button></header>
    <div className="grid grid-cols-1 gap-4 xl:grid-cols-12">
      <section className="glass-card-static p-4 xl:col-span-7"><h2 className="mb-3 flex items-center gap-2 text-sm font-semibold"><ShieldAlert size={16} className="text-rose-300" />Active Risks</h2><div className="space-y-2">{risks.map(([title, time, description, affected, status, Icon, color]) => <div key={title} className="flex gap-3 rounded-lg border border-cyan-400/20 bg-[#082653] p-3"><Icon size={17} className={color} /><div className="flex-1"><strong className="block text-xs">{title}</strong><span className="text-[9px] text-slate-400">{time} · {description}</span><span className="mt-1 block text-[9px] text-slate-500">Affected: {affected}</span></div><strong className={`text-[9px] ${color}`}>{status}</strong></div>)}</div></section>
      <section className="glass-card-static p-4 xl:col-span-5"><h2 className="mb-3 flex items-center gap-2 text-sm font-semibold"><AlertTriangle size={16} className="text-rose-300" />Alert Details</h2><p className="text-[10px] text-slate-300">Severity: <strong className="text-rose-300">HIGH</strong> · Detected: {data?.headerInfo?.time || '10:41 UTC'}</p><p className="mt-2 text-[10px] text-cyan-200">Trigger: <span className="text-slate-300">Rapid environmental deterioration</span></p><div className="mt-3 grid grid-cols-2 gap-2 text-[9px] text-slate-300">{reasons.slice(0, 4).map((reason) => <p key={reason.text}>{reason.text}: <strong className="text-rose-300">{reason.highlight}</strong></p>)}</div><p className="mt-3 text-[9px] text-slate-400">Affected systems: Outdoor Operations, Power, Heating</p><p className="mt-3 text-[10px] text-cyan-200">Recommended actions</p><p className="text-[9px] text-slate-300">Restrict outdoor activity · Monitor heating demand · Verify personnel status</p></section>
      <section className="glass-card-static p-4 xl:col-span-5"><div className="mb-3 flex justify-between"><h2 className="flex items-center gap-2 text-sm font-semibold"><ClipboardList size={16} className="text-cyan-300" />Emergency Checklist</h2><span className="text-[10px] text-cyan-200">{done}/{checklist.length} complete</span></div><div className="mb-3 h-1.5 rounded-full bg-slate-700"><div className="h-full rounded-full bg-cyan-400" style={{ width: `${checklist.length ? (done / checklist.length) * 100 : 0}%` }} /></div><div className="space-y-2">{checklist.map((item, index) => { const isDone = completed[index] || item.checked; return <button type="button" key={item.label} onClick={() => setCompleted((items) => ({ ...items, [index]: !isDone }))} className="flex w-full items-center gap-2 text-left text-[10px] text-slate-300">{isDone ? <CheckCircle2 size={14} className="text-emerald-400" /> : <span className="h-3.5 w-3.5 rounded-full border border-slate-500" />}{item.label}</button>; })}</div></section>
      <section className="glass-card-static overflow-hidden p-4 xl:col-span-7"><div className="mb-3 flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-semibold"><FileText size={16} className="text-cyan-300" />Incident Management</h2><button type="button" className="flex items-center gap-1 rounded-lg border border-cyan-400/20 px-3 py-1.5 text-[9px] text-cyan-300"><Plus size={12} />New Incident</button></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-[9px]"><thead className="text-slate-500"><tr>{['ID', 'Severity', 'Affected System', 'Description', 'Status', 'Timestamp'].map((heading) => <th key={heading} className="p-2">{heading}</th>)}</tr></thead><tbody>{incidentHistory.map((incident, index) => <tr key={incident[0]} onClick={() => setSelected(index)} className={`cursor-pointer border-t border-white/5 ${selected === index ? 'bg-cyan-500/10' : ''}`}><td className="p-2 text-white">{incident[0]}</td><td className="p-2 text-rose-300">{incident[2]}</td><td className="p-2">{incident[3]}</td><td className="p-2">{incident[4]}</td><td className="p-2">{incident[5]}</td><td className="p-2">{incident[6]}</td></tr>)}</tbody></table></div><div className="mt-3 rounded-lg bg-[#082653] p-3 text-[10px] text-slate-300"><strong className="text-white">Incident detail · {selectedIncident[0]}: {selectedIncident[1]}</strong><p className="mt-1">{selectedIncident[4]} — {selectedIncident[5]} at {selectedIncident[6]}.</p></div></section>
      <section className="glass-card-static p-4 xl:col-span-12"><h2 className="mb-3 text-sm font-semibold">Reports</h2><div className="flex flex-wrap gap-2">{['Incident Report', 'Weather Report', 'Station Report', 'Export Report'].map((report) => <button key={report} type="button" className="rounded-lg border border-cyan-400/20 px-3 py-2 text-[10px] text-cyan-200 hover:bg-cyan-400/10">{report}</button>)}</div></section>
    </div></div></div>;
}
