import React, { useState } from 'react';
import { CheckCircle2, ClipboardList, MessageSquare, ShieldCheck, Users } from 'lucide-react';
import { useDashboard } from '../DashboardContext';

const tasks = ['Monitor battery level', 'Inspect communication link', 'Review weather conditions', 'Confirm personnel status'];
const events = ['High Weather Risk detected', 'Power load increased', 'Communication degradation detected'];

export default function ShiftHandover() {
  const { data } = useDashboard();
  const [notes, setNotes] = useState('');
  const [saved, setSaved] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const [tasksDone, setTasksDone] = useState([]);
  const risk = data?.currentWeather?.weatherRisk || 0;
  const systems = [['Power', 'WATCH', 'text-amber-300'], ['Heating', 'NORMAL', 'text-emerald-300'], ['Communication', 'DEGRADED', 'text-rose-300'], ['Fuel', '68%', 'text-cyan-200'], ['Water', 'NORMAL', 'text-emerald-300']];
  return <div className="min-h-full overflow-x-hidden"><div className="mx-auto max-w-[1360px] px-4 pb-8 md:px-6"><header className="flex flex-wrap items-center justify-between gap-4 py-5"><div><h1 className="text-2xl font-bold text-white">Shift Handover</h1><p className="text-xs text-slate-400">What happened during this shift, and what the next team needs to watch</p></div><span className="rounded-full bg-cyan-400/10 px-3 py-2 text-[10px] text-cyan-200">Bharati · {data?.headerInfo?.time}</span></header>
    <section className="glass-card-static mb-4 grid grid-cols-2 gap-3 p-4 md:grid-cols-4"><div><span className="text-[10px] text-slate-500">Station</span><strong className="mt-1 block text-xs">Bharati</strong></div><div><span className="text-[10px] text-slate-500">Current Shift</span><strong className="mt-1 block text-xs">Day Shift</strong><small className="text-[9px] text-slate-400">06:00–18:00 UTC</small></div><div><span className="text-[10px] text-slate-500">Overall Status</span><strong className={`mt-1 block text-xs ${risk >= 50 ? 'text-amber-300' : 'text-emerald-300'}`}>{risk >= 50 ? 'WATCH' : 'NORMAL'}</strong></div><div><span className="text-[10px] text-slate-500">Shift Range</span><strong className="mt-1 block text-xs">{data?.headerInfo?.date || 'Today'}</strong></div></section>
    <div className="grid grid-cols-1 gap-4 xl:grid-cols-12"><main className="space-y-4 xl:col-span-8"><section className="glass-card-static p-4"><h2 className="mb-3 flex items-center gap-2 text-sm font-semibold"><ClipboardList size={16} className="text-cyan-300" />Important Events</h2><div className="space-y-2">{events.map((event, index) => <div key={event} className="rounded-lg border border-cyan-400/20 bg-[#082653] p-3 text-[10px]"><span className="text-slate-500">{['10:41 UTC', '10:35 UTC', '10:20 UTC'][index]}</span><strong className="ml-3 text-slate-200">{event}</strong></div>)}</div></section><section className="glass-card-static p-4"><h2 className="mb-3 flex items-center gap-2 text-sm font-semibold"><MessageSquare size={16} className="text-cyan-300" />Handover Notes</h2><textarea value={notes} onChange={(event) => { setNotes(event.target.value); setSaved(false); }} maxLength={1000} placeholder="Heavy weather expected over the next 6 hours. Outdoor operations restricted. Monitor power consumption." className="h-28 w-full resize-none rounded-lg border border-cyan-400/20 bg-[#082653] p-3 text-[10px] text-white outline-none placeholder:text-slate-500" /><div className="mt-2 flex items-center justify-between"><span className="text-[9px] text-slate-500">{notes.length}/1000</span><button type="button" onClick={() => setSaved(true)} className="btn-gradient rounded-lg px-4 py-2 text-[10px] font-semibold">{saved ? 'Notes Saved' : 'Save Notes'}</button></div></section></main>
      <aside className="space-y-4 xl:col-span-4"><section className="glass-card-static p-4"><h2 className="mb-3 flex items-center gap-2 text-sm font-semibold"><ShieldCheck size={16} className="text-cyan-300" />Systems Requiring Attention</h2><div className="space-y-2">{systems.map(([name, status, color]) => <div key={name} className="flex justify-between rounded-lg bg-[#082653] p-2 text-[10px]"><span>{name}</span><strong className={color}>{status}</strong></div>)}</div></section><section className="glass-card-static p-4"><h2 className="mb-3 text-sm font-semibold">Pending Tasks</h2><div className="space-y-2">{tasks.map((task, index) => <button type="button" key={task} onClick={() => setTasksDone((items) => items.includes(index) ? items.filter((item) => item !== index) : [...items, index])} className="flex w-full items-center gap-2 text-left text-[10px] text-slate-300">{tasksDone.includes(index) ? <CheckCircle2 size={14} className="text-emerald-300" /> : <span className="h-3.5 w-3.5 rounded-full border border-slate-500" />}{task}</button>)}</div></section><section className="glass-card-static p-4"><h2 className="mb-3 flex items-center gap-2 text-sm font-semibold"><Users size={16} className="text-cyan-300" />Acknowledgement</h2><p className="text-[10px] text-slate-400">Outgoing Operator</p><strong className="text-xs">Team Alpha</strong><p className="mt-3 text-[10px] text-slate-400">Incoming Operator</p><strong className="text-xs">Team Bravo</strong><button type="button" onClick={() => setConfirmed(true)} className="btn-gradient mt-4 w-full rounded-lg py-2 text-[10px] font-semibold">{confirmed ? 'Handover Confirmed' : 'Confirm Handover'}</button></section></aside>
    </div></div></div>;
}
