import React from 'react';
import { Database, Droplets, Radio, ShieldCheck, TestTube, Zap } from 'lucide-react';
import BharatiDigitalTwin from './BharatiDigitalTwin.jsx';
import { useDashboard } from '../DashboardContext';

const healthSystems = [['Power System', Zap], ['Heating', Zap], ['Water Recycling', Droplets], ['Fuel Storage', Database], ['Communication', Radio], ['Research Labs', TestTube], ['Living Quarters', ShieldCheck], ['Storage', Database], ['Security', ShieldCheck]];

export default function DigitalTwin() {
  const { data } = useDashboard();
  const impact = data?.stationImpact || {};
  const buildings = data?.digitalTwinData?.buildings || [];
  const statusFor = (name) => buildings.find((building) => building.name === name || (name === 'Communication' && building.name === 'Comm. System'))?.status || 'Normal';
  const resources = [['Power usage', impact.powerDemand ?? 0, 'bg-blue-500'], ['Fuel level', Math.max(0, 100 - (impact.fuelConsumption ?? 0)), 'bg-emerald-400'], ['Water supply', Math.max(0, 100 - (impact.heatingDemand ?? 0) / 2), 'bg-cyan-400'], ['Internet bandwidth', Math.max(0, 100 - (data?.currentWeather?.weatherRisk ?? 0)), 'bg-violet-400']];
  return <div className="min-h-screen overflow-y-auto bg-[#061224] p-4 text-slate-100 md:p-6">
    <header className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-white">Digital Twin</h1><p className="mt-1 text-xs text-slate-400">Infrastructure monitoring for Bharati Research Station</p></div><span className="rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1.5 text-[10px] font-medium text-emerald-300">Live infrastructure feed · {data?.headerInfo?.time}</span></header>
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-12"><section className="min-h-[600px] overflow-hidden rounded-2xl border border-slate-700/70 bg-[#0b1b33] lg:col-span-8"><BharatiDigitalTwin /></section><aside className="space-y-4 lg:col-span-4"><section className="rounded-2xl border border-slate-700/70 bg-[#0b1b33] p-4"><h2 className="mb-3 text-xs font-semibold">System Health</h2><div className="grid grid-cols-2 gap-2">{healthSystems.map(([name, Icon]) => { const status = statusFor(name); const watch = status !== 'Normal'; return <div key={name} className="rounded-xl border border-slate-700 bg-[#071326] p-3"><Icon size={15} className={watch ? 'text-amber-300' : 'text-cyan-300'} /><span className="mt-2 block text-[10px] text-slate-200">{name}</span><strong className={watch ? 'text-[9px] text-amber-300' : 'text-[9px] text-emerald-300'}>{watch ? 'WATCH' : 'NORMAL'}</strong></div>; })}</div></section><section className="rounded-2xl border border-slate-700/70 bg-[#0b1b33] p-4"><h2 className="mb-4 text-xs font-semibold">Resource Monitoring</h2><div className="space-y-4">{resources.map(([label, value, color]) => <div key={label}><div className="mb-1 flex justify-between text-[10px]"><span className="text-slate-300">{label}</span><strong>{Math.round(value)}%</strong></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full ${color}`} style={{ width: `${value}%` }} /></div></div>)}</div></section></aside></div>
    <section className="mt-4 rounded-2xl border border-slate-700/70 bg-[#0b1b33] p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xs font-semibold">Power System</h2><p className="mt-1 text-[10px] text-amber-300">Status: WATCH</p><div className="mt-3 grid grid-cols-2 gap-x-6 gap-y-1 text-[10px] text-slate-300"><span>Power Generation: <strong>78%</strong></span><span>Battery: <strong>40%</strong></span><span>Load: <strong>{impact.powerDemand ?? 82}%</strong></span><span>Fuel Dependency: <strong>Medium</strong></span></div></div><div className="max-w-sm text-[10px] text-slate-400"><p><strong className="text-cyan-200">Current Issue:</strong> High heating demand</p><p className="mt-1"><strong className="text-cyan-200">Impact:</strong> Battery reserve may decrease during prolonged blizzard.</p><p className="mt-1"><strong className="text-cyan-200">Recommended:</strong> Reduce non-essential loads</p></div></div></section>
  </div>;
}
